---
title: "Ecological Modelling"
output: 
  html_document:
    toc: FALSE
---


Welcome to the **Ecological Modelling** course website

This website contains the content of the *Ecological Modelling* course taught by Prof. Dr. [Jelena H. Pantel](http://jhpantel.com) in the MS Aquatic Biology program at the University of Duisburg-Essen.

# Announcement 1
We will not have class in-person on Thursday 22-12-2022. Instead, I will schedule a 1-on-1 Zoom meeting with each of you, next week and the week of January 9 2023 (you can choose). You can sign up for a meeting time using this Google calendar:

https://docs.google.com/spreadsheets/d/11Rkqy6OsO-YtqsNrJx1EXwnqjfp0UOviydy2IS4D-VA/edit?usp=sharing

The Zoom information is given on that website, but you can also follow this link (I will post the meeting ID and pass code on Moodle).

https://us05web.zoom.us/j/4098623635?pwd=YjhkWDhYeW0rMStnKzk0TWx6NWpCdz09

# Announcement 2
+ You need to have completed 3 exercises, as R scripts called "ude-ecomod-hw1.R", "ude-ecomod-hw2.R", and "ude-ecomod-hw2.R". The instructions to complete this are in Steps 1-9 here in [__Reading Guide 5__](./w7_readguide.html). I will check your Github and see that I can access all of the files. I will also check my email to look at the files some of you have sent me.

+ You should get started on your Course Project 1. You can find information about that on the course homepage, in the menu under Projects --> Project 1. Let me know if you need more resources, I will be happy to share textbook chapters (with R code!) for the various models that have been discussed.

+ For class 15-12-2022, as indicated in the course schedule, please read [__Grainger et al. 2022__](./r6_Grainger_2022.pdf) and complete [__Reading Guide 7__](./w9_readguide.html).

# Course Information

This is a seminar course, held from 16-18h on Thursdays, in room S05 R03 H8. I am available to meet Wednesdays 5-6pm over Zoom, but you must e-mail in advance of that time to let me know if you want to meet. The grade in the course will stem from 2 projects. Project 1 will be creating a "cheat sheet", or a 1-2 page document that provides an overview of a theoretical model in Ecology or Limnology. Project 2 will be a hands-on application, where you will take actual data and test predictions from theoretical models.

# Course Description

In this course, we will cover two broad topics: (1) we will get an overview of models that are used in Ecology, Evolution, and Aquatic Biology and (2) we will learn how to fit actual, observed data to theoretical models. We will gain proficiency in computational ecology, as we will use the statistical programming language R to work with models and data. The classroom is equipped with computer workstations.

# Website content

Click the links in the menu above to look around. We can also message each other using the course Moodle page: (https://moodle.uni-due.de/)


# Notes

This website is a collection of regular (R)Markdown documents.

If you are new to R Markdown, you can learn more about it [on the R Markdown website](https://rmarkdown.rstudio.com/). 


