---
title: "Ecological Modelling - Winter 2023-2024 - Schedule"
author: "Jelena H. Pantel"
institute: "University of Duisburg-Essen"
date: "`r file.mtime(knitr::current_input())`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course calendar
This is the current course schedule for the class. Things will change, so check regularly for updates.

__Please do all readings in advance of the scheduled course period. Each reading is accompanied by a document giving some guidelines to prepare yourself to discuss the reading in class.__ 


| **Module Topic**   | **Date** | **Readings** | **Class documents** |
| --- | --- | --- | --- |
| Module 1.1 – Introduction to Models in Ecology, Part 1 | 11-10-2023 | none | 1. [__Lecture 1.1__](./L1.1.pdf) |
| Module 1.1 – Introduction to Models in Ecology, Part 1 | 12-10-2023 | none | 1. [__Exercise 1.1__](./E1.1.pdf), 2. [__Solutions 1.1__](./SE1.1.pdf)
| CLASS CANCELLED | 18-10-2023 | TO BE | RESCHEDULED |
| Module 1.2 – Introduction to Models in Ecology, Part 2  | 19-10-2023 | 1. [__Jackson et al. 2000__](./r1_Jackson_2000.pdf), 2. [__Otto & Day Ch2__](./r2_OttoDay_Ch2.pdf), 3. [__Reading Guide 1.2__](./RG1.2.html)| [__Lecture 1.2__](./L1.2.pdf) |
| Module 1.2 – Introduction to Models in Ecology, Part 2  | 19-10-2023 | none | 1. [__Exercise 1.2__](./E1.2.pdf), 2. [__Solutions 1.2__](./SE1.2.pdf) |
| Module 2.1 – Survey of ecological models, Part 1 | 25-10-2023 | 1. [__Otto & Day Ch3__](./r3_OttoDay_Ch3.pdf) (3.1,3.2), 2. [__Reading Guide 2.1__](./RG2.1.html)  | 1. [__Lecture 2.1a__](./L2.1a.pdf) 2. [__Lecture Notes 2.1__](./L2.1_notes.html) |
| Module 2.1 – Survey of ecological models, Part 1 | 26-10-2023 | none  | 1. [__Exercise 2.1__](./E2.1.pdf), 2. [__Solutions 2.1__](./SE2.1.pdf) |
| no class, holiday  | 01-11-2022 | none | none |
| topic To Be Determined  | 02-11-2022 | none | none |
| Module 2.2 – Survey of ecological models, Part 2  | 08-11-2023 | 1. __Otto & Day Ch3__ (3.4,3.6), 2. [__Reading Guide 2.2__](./RG2.2.html) | 1. [__Lecture Notes 2.2__](./L2.2_notes.html), 2. [__Lecture 2.1b__](./L2.1b.pdf) |
| Module 2.2 – Survey of ecological models, Part 2  | 09-11-2023 | none | 1. [__Exercise 2.2__](./E2.2.pdf), 2. __Solutions 2.2__ |
| --- | --- | --- | --- |
| Module 3.1 – Models and data in ecology case studies, Part 1 | 15-11-2023 | 1. [__Courchamp et al. 1999__](./r4.1_Courchamp_1999.pdf), 2. [__Reading Guide 3.1__]  |  |
| Module 3.2 – Models and data in ecology case studies, Part 2 | 16-11-2023 | 1. [__Lahaye et al. 1994__](./r4_Lahaye_1994.pdf), 2. [__Reading Guide 3.2__](./RG3.2.html)  | 1. [__Exercise 3.2__], 2. [__Lecture 3.1__](./L3.1.pdf) |
| Module 4.1 – Fitting empirical data to models, Part 1 | 22-11-2023 | [__Muhlbauer et al. 2020__](./r7_Muhlbauer_2020.pdf) | [__Lecture 4.1__](./L4.1.pdf) |
| Module 4.1 – Fitting empirical data to models, Part 1 | 23-11-2023 | none | 1. [__Exercise 4.1__](./E4.1.html), 2. __Solutions 4.1__  |
| Module 4.2 – Fitting empirical data to models, Part 2 | 29-11-2023 | none | [__Lecture 4.2__](./L4.2.pdf) |
| Module 4.2 – Fitting empirical data to models, Part 2 | 30-11-2023 | none | 1. __Exercise 4.2__, 2. __Solutions 4.2__ |
| Module 4.3 – Fitting empirical data to models, Part 3. | 06-12-2023 | 1. [__Siren et al. 2018__](./r8_Siren_2018.pdf) | 1. [__Exercise 4.3__](./E4.3.pdf), 2. __Solutions 4.3__ |
| Module 4.3 – Fitting empirical data to models, Part 3. **Course project 1 & 2 (DUE)** | 07-12-2023 | to be determined | to be determined |
